// <auto-generated />
using System;
using ARMApocalypseSASAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ARMApocalypseSASAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221230084529_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.12");

            modelBuilder.Entity("ARMApocalypseSASAPI.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = "38604219-8499-464b-8a1b-c6fbd226773f",
                            CreatedAt = new DateTime(2022, 12, 30, 8, 45, 28, 912, DateTimeKind.Utc).AddTicks(3964),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Water",
                            Price = 4m,
                            UpdatedAt = new DateTime(2022, 12, 30, 8, 45, 28, 912, DateTimeKind.Utc).AddTicks(3966)
                        },
                        new
                        {
                            Id = "1084e310-6a07-4d9c-92a6-8225ab696e25",
                            CreatedAt = new DateTime(2022, 12, 30, 8, 45, 28, 912, DateTimeKind.Utc).AddTicks(4004),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Food",
                            Price = 3m,
                            UpdatedAt = new DateTime(2022, 12, 30, 8, 45, 28, 912, DateTimeKind.Utc).AddTicks(4004)
                        },
                        new
                        {
                            Id = "1c06a133-72e2-462a-8cad-f5d1865ef417",
                            CreatedAt = new DateTime(2022, 12, 30, 8, 45, 28, 912, DateTimeKind.Utc).AddTicks(4008),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Medication",
                            Price = 2m,
                            UpdatedAt = new DateTime(2022, 12, 30, 8, 45, 28, 912, DateTimeKind.Utc).AddTicks(4008)
                        },
                        new
                        {
                            Id = "5d7acdd0-3a9b-47ca-89f1-a8228ac136f2",
                            CreatedAt = new DateTime(2022, 12, 30, 8, 45, 28, 912, DateTimeKind.Utc).AddTicks(4010),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ammunition",
                            Price = 1m,
                            UpdatedAt = new DateTime(2022, 12, 30, 8, 45, 28, 912, DateTimeKind.Utc).AddTicks(4011)
                        });
                });

            modelBuilder.Entity("ARMApocalypseSASAPI.Models.Survivor", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInfected")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LastLocationLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("LastLocationLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Survivors");
                });

            modelBuilder.Entity("ARMApocalypseSASAPI.Models.SurvivorInfectionReport", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfReport")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportedSurvivorID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportingSurvivorID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportedSurvivorID");

                    b.HasIndex("ReportingSurvivorID");

                    b.ToTable("SurvivorInfectionReports");
                });

            modelBuilder.Entity("ARMApocalypseSASAPI.Models.TradeItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SurvivorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPoints")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SurvivorId");

                    b.ToTable("TradeItems");
                });

            modelBuilder.Entity("ARMApocalypseSASAPI.Models.SurvivorInfectionReport", b =>
                {
                    b.HasOne("ARMApocalypseSASAPI.Models.Survivor", "ReportedSurvivor")
                        .WithMany()
                        .HasForeignKey("ReportedSurvivorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ARMApocalypseSASAPI.Models.Survivor", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReportingSurvivorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedSurvivor");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("ARMApocalypseSASAPI.Models.TradeItem", b =>
                {
                    b.HasOne("ARMApocalypseSASAPI.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ARMApocalypseSASAPI.Models.Survivor", "Survivor")
                        .WithMany("OwnTradeItems")
                        .HasForeignKey("SurvivorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Survivor");
                });

            modelBuilder.Entity("ARMApocalypseSASAPI.Models.Survivor", b =>
                {
                    b.Navigation("OwnTradeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
